# Generated by Django 4.2.19 on 2025-03-16 01:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("patron", "Patron"), ("librarian", "Librarian")],
                        default="patron",
                        max_length=10,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="changed_user_set", to="auth.group"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userprofile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="changed_user_permissions",
                        to="auth.permission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Checked out", "Checked out"),
                        ],
                        default="Available",
                        max_length=13,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("LikeNew", "Like New"),
                            ("Good", "Good"),
                            ("Acceptable", "Acceptable"),
                            ("Poor", "Poor"),
                        ],
                        default="Acceptable",
                        max_length=13,
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Romance", "Romance"),
                            ("Adventure", "Adventure"),
                            ("Mystery", "Mystery"),
                            ("Non-fiction", "Non-fiction"),
                            ("Fantasy", "Fantasy"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Shannon Library", "Shannon Library"),
                            (
                                "Student Health and Wellness",
                                "Student Health and Wellness",
                            ),
                            ("Gibbons", "Gibbons"),
                            ("Rice Hall", "Rice Hall"),
                        ],
                        max_length=27,
                    ),
                ),
                ("comments", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(max_length=200)),
                (
                    "lender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
