# Generated by Django 4.2.19 on 2025-04-12 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_book_isbn_alter_comments_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionsRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("waiting", "Waiting"),
                            ("denied", "Denied"),
                        ],
                        default="waiting",
                        max_length=10,
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="catalog.collection",
                    ),
                ),
                (
                    "librarian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collection_permission_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patron",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_view_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pickup_datetime",
                    models.DateTimeField(default=users.models.default_time),
                ),
                ("duration", models.PositiveIntegerField(default=1)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("waiting", "Waiting"),
                            ("denied", "Denied"),
                            ("expired", "Expired"),
                        ],
                        default="waiting",
                        max_length=10,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="catalog.book",
                    ),
                ),
                (
                    "librarian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patron",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="bookrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("status", "denied"), _negated=True),
                    ("status", "expired"),
                    _connector="OR",
                ),
                fields=("book", "patron"),
                name="unique_open_request",
            ),
        ),
    ]
