# Generated by Django 4.2.19 on 2025-04-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_collectionsrequest_bookrequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookrequest",
            name="notified",
            field=models.BooleanField(default=False),
        ),
    ]
