# Generated by Django 5.1.7 on 2025-04-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_bookrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookrequest",
            name="pickup_time",
        ),
        migrations.AddField(
            model_name="bookrequest",
            name="pickup_hour",
            field=models.IntegerField(default=9),
        ),
    ]
