# Generated by Django 4.2.19 on 2025-04-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_bookrequest_notified"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="join_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
