# Generated by Django 5.1.7 on 2025-04-07 02:57

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("users", "0003_remove_bookrequest_pickup_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookrequest",
            name="pickup_hour",
        ),
        migrations.AddField(
            model_name="bookrequest",
            name="pickup_datetime",
            field=models.DateTimeField(default=users.models.default_time),
        ),
        migrations.CreateModel(
            name="CollectionsRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("waiting", "Waiting"),
                            ("denied", "Denied"),
                        ],
                        default="waiting",
                        max_length=10,
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="catalog.collection",
                    ),
                ),
                (
                    "librarian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collection_permission_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patron",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_view_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
