# Generated by Django 4.2.19 on 2025-02-21 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0004_user_delete_userprofile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="UserProfile",
        ),
    ]
