# Generated by Django 5.1.7 on 2025-04-07 03:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("users", "0004_remove_bookrequest_pickup_hour_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bookrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "denied"), _negated=True),
                fields=("book", "patron"),
                name="unique_open_request",
            ),
        ),
    ]
