# Generated by Django 5.1.7 on 2025-04-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_bookrequest_unique_open_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookrequest",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookrequest",
            name="duration",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
