# Generated by Django 4.2.19 on 2025-03-16 01:40

import app.storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("published_date", models.DateField()),
                ("genre", models.CharField(max_length=100)),
                ("summary", models.TextField()),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=app.storage_backend.MediaStorage(),
                        upload_to="book_covers/",
                    ),
                ),
            ],
        ),
    ]
