# Generated by Django 5.1.7 on 2025-03-24 00:19

import app.storage_backend
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=20)),
                ("isbn", models.CharField(max_length=13, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Checked out", "Checked out"),
                        ],
                        default="Available",
                        max_length=13,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("LikeNew", "Like New"),
                            ("Good", "Good"),
                            ("Acceptable", "Acceptable"),
                            ("Poor", "Poor"),
                        ],
                        default="Acceptable",
                        max_length=13,
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Romance", "Romance"),
                            ("Adventure", "Adventure"),
                            ("Mystery", "Mystery"),
                            ("Non-fiction", "Non-fiction"),
                            ("Fantasy", "Fantasy"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Shannon Library", "Shannon Library"),
                            (
                                "Student Health and Wellness",
                                "Student Health and Wellness",
                            ),
                            ("Gibbons", "Gibbons"),
                            ("Rice Hall", "Rice Hall"),
                        ],
                        default="Shannon Library",
                        max_length=27,
                    ),
                ),
                ("comments", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(default=" ", max_length=200)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=app.storage_backend.MediaStorage(),
                        upload_to="book_covers/",
                    ),
                ),
                (
                    "lender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
