# Generated by Django 4.2.19 on 2025-04-12 19:58

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                help_text="Enter 13-digit ISBN: ",
                max_length=13,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="ISBN must be exactly 13 digits!", regex="^\\d{13}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="comments",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="comments",
            name="rating",
            field=models.IntegerField(),
        ),
    ]
