# Generated by Django 4.2.19 on 2025-03-24 20:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='summary',
        ),
        migrations.AddField(
            model_name='book',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('LikeNew', 'Like New'), ('Good', 'Good'), ('Acceptable', 'Acceptable'), ('Poor', 'Poor')], default='Acceptable', max_length=13),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='lender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.CharField(choices=[('Shannon Library', 'Shannon Library'), ('Student Health and Wellness', 'Student Health and Wellness'), ('Gibbons', 'Gibbons'), ('Rice Hall', 'Rice Hall')], default='Shannon Library', max_length=27),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Checked out', 'Checked out')], default='Available', max_length=13),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Romance', 'Romance'), ('Adventure', 'Adventure'), ('Mystery', 'Mystery'), ('Non-fiction', 'Non-fiction'), ('Fantasy', 'Fantasy')], max_length=100),
        ),
    ]
