# Generated by Django 4.2.19 on 2025-03-15 20:09

import app.storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_author_delete_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=app.storage_backend.MediaStorage(), upload_to='book_covers/'),
        ),
    ]
