# Generated by Django 4.2.19 on 2025-04-12 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0002_alter_book_isbn_alter_comments_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="lender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listed_books",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
