# Generated by Django 4.2.19 on 2025-03-24 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_lender_remove_book_isbn_remove_book_published_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('books', models.ManyToManyField(blank=True, related_name='collections', to='catalog.book')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateCollection',
            fields=[
                ('collection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.collection')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='private_collections', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('catalog.collection',),
        ),
    ]
