# Generated by Django 4.2.19 on 2025-03-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_collection_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
